### ISSUE TITLE
Unable to run hardhat from @oasislabs/hardhat package

### ISSUE THREAD

**Issue by CedarMist** [oasislabs/NomicFoundation-hardhat#6]
### Version of Hardhat

latest

### What happened?

```
$ ./node_modules/.bin/hardhat
Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.

HardhatError: HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.
    at main (/src/blah/node_modules/@oasislabs/hardhat/src/internal/cli/cli.ts:180:13)
    at Object.<anonymous> (/src/blah/node_modules/@oasislabs/hardhat/src/internal/cli/cli.ts:377:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/src/blah/node_modules/@oasislabs/hardhat/src/internal/cli/bootstrap.ts:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

### Minimal reproduction steps

```
npm init
# then add oasislabs packages
npm install --save-dev
```

example package.json

```json
{
  "name": "blah",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@oasislabs/hardhat": "^2.14.7",
    "@oasislabs/opengsn-cli": "^3.0.0-beta.3",
    "@oasislabs/opengsn-relay": "^3.0.0-beta.3"
  }
}
```

Tried removing opengsn from package.json, removing package lock file then re-installing oasislabs/hardhat via `yarn` and I get the same error.

**Comment by xmzheng** [comment]
can you try the following commands: 

```
npm init -y
npm install --save-dev hardhat@npm:@oasislabs/hardhat
npx hardhat
```

**Comment by CedarMist** [comment]
Thank you, this has resolved the problem. My package.json looks like:

```json
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^3.0.0",
    "hardhat": "npm:@oasislabs/hardhat@^2.14.7",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.3"
  }
```
